name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 18.9.0
        - run: npm CI
        - run: npm run build
      - name: install php dependencies
        uses: baschny/php-composer-action@v2
        with:
          composer-version: "~2.0"
        - run: php composer.phar install
        - run: cp .env.example .env
      - name: deploy to CPanel via ftp
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "."
          dist_target_dir: "."

